[profile.default]
auto_detect_solc = false
bytecode_hash = "none"
fuzz_runs = 256
gas_reports = ["*"]
libs = ["lib"]
optimizer = true
optimizer_runs = 10_000
out = "out"
solc = "0.8.17"
src = "src"
test = "test"

[profile.ci]
fuzz_runs = 1_000
verbosity = 4

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = {key = "${ETHERSCAN_API_KEY}"}
mainnet = {key = "${ETHERSCAN_API_KEY}"}

[doc]
out = "docs"
title = "Floor"
book = "./book.toml"
repository = "https://github.com/FloorDAO/floor-v2"
ignore = ["**/*.t.sol"]

[fmt]
line_length = 140
tab_width = 4
bracket_spacing = false
int_types = "short"
multiline_func_header = "attributes_first"
quote_style = "single"
number_underscore = "preserve"
override_spacing = true
wrap_comments = false
ignore = []

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
