// SPDX-License-Identifier: MIT

pragma solidity ^0.8.0;

interface ITransferTreasuryFundsAndGenerateAllocationsZap {
    /**
     * To help save gas this zap concatenates three key calls from the {OptionExchange}
     * into a singular call. This will transfer assets from the {Treasury}, create a
     * pool for the assets and then triggers our allocations to be generated by the
     * connected ChainLink oracle.
     *
     * The following functions will be called in this order:
     *
     *  - deposit
     *  - createPool
     *  - generateAllocations
     */
    function execute(address token, uint amount, uint maxDiscount, uint expires) external;
}
