[book]
src = 'src'
title = 'Floor'
[output.html]
no-section-label = true
additional-js = ['solidity.min.js']
additional-css = ['book.css']
git-repository-url = 'https://github.com/FloorDAO/floor-v2'

[output.html.fold]
enable = true
